DB_HOST: localhost
DB_PORT: 5433
DB_NAME: kotlin
DB_USERNAME: postgres
DB_PASSWORD: root
JWT_EXPIRATION_TIME: 600000
JWT_SECRET_KEY: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCr+MKSbjTwLCnZ+H7K2qzjfIeLPZ/KF4l3MXcNyAbUWLa7EK20+JVGNkHgVcvtPCWS6wBZj7MG4nNxDnL50UWJxRAQUaMbzS8tnZFp0dou4KtZ/+7dOfs6VWv0sRWp1FY+kI37DfgAiaHY1SrrroQ+8A7YLhAc7GthS2T6WZQJqwIDAQAB